### ISSUE TITLE
Removing boxing of parameters to device kernel (for both CPU and GPU kernels)

### ISSUE THREAD

**Issue by yanyh15** [passlab/rexompiler#69]
Orignally, boxing is needed for passing parameters to kernel function using struct. Right now, we remove the use of boxing.

**Comment by ouankou** [comment]
According to Dr. Yan, the usage of boxing was used in ROSE because GOMP requires a struct to hold all the parameters. However, now we are replacing GOMP with LLVM OpenMP runtime, and LLVM doesn't have such a requirement. To conduct a more conventional transformation and unify the transformation in C/C++ and Fortran, we remove the boxing of parameters to device kernels.

It's done in commit https://github.com/passlab/rexompiler/commit/f625f891a36dc7592058acb6638cba26e728a59c.
